LOCATION_MAPPING = {
    -- Garden of Spring
    [0x100] = {"@Garden of Spring/Snowy Forest/Tools of the Explorer Found"},
    [0x101] = {"@Garden of Spring/Snowy Forest/Tool of Mining Found"},
    [0x102] = {"@Garden of Spring/Snowy Forest/Super Spore Received"},
    [0x103] = {"@Lake of Bloom/Smushi's Home/Conch Shell Received"},
    [0x200] = {"@Garden of Spring/Mycena Entry/Garden Map Found"},
    [0x201] = {"@Garden of Spring/Mycena Entry/Yellow Shrine Energy Spore"},
    [0x202] = {"@Garden of Spring/Bolete Beach/Pink Shrine Energy Spore"},
    [0x203] = {"@Garden of Spring/Ancient Passage/Blue Shrine Energy Spore"},
    [0x204] = {"@Garden of Spring/Bolete Beach/Blade of Power Purchase"},
    [0x205] = {"@Garden of Spring/Anemone Woods/Anemone Woods Wind Essence"},
    [0x206] = {"@Garden of Spring/Mycena Entry/Mycology Journal Unlock"},
    [0x207] = {"@Garden of Spring/Anemone Woods/Band of Elasticity Found"},
    [0x208] = {"@Garden of Spring/Myrtle Pools/Myrtle Pools Wind Essence"},
    [0x209] = {"@Garden of Spring/Myrtle Pools/Myrtle Pools Blueberry Purchase"},
    [0x20B] = {"@Garden of Spring/Myrtle Pools/Ancient Relic 1 Found"},
    [0x20A] = {"@Garden of Spring/Myrtle Pools/Ancient Relic 2 Found"},
    [0x20C] = {"@Garden of Spring/Crystal Caves/Crystal Cave Blueberry Found"},
    [0x20D] = {"@Garden of Spring/Mycena Entry/Tool of Writing Found"},
    [0x20E] = {"@Garden of Spring/Myrtle Pools/Ancient Relics Returned"},

    -- Forest of Fall
    [0x300] = {"@Forest of Fall/Waxcap Falls/Forest Map Found"},
    [0x301] = {"@Forest of Fall/Waxcap Falls/Sturdy Hooks Purchase"},
    [0x302] = {"@Forest of Fall/Waxcap Falls/Nectar Collector"},
    [0x303] = {"@Forest of Fall/Cryptic Caverns/Explosive Powder 1 Found"},
    [0x304] = {"@Forest of Fall/Dark Cave/Explosive Powder 2 Found"},
    [0x305] = {"@Forest of Fall/Maple Sanctuary/Secret Password Found"},
    [0x306] = {"@Forest of Fall/Maple Sanctuary/Super Essence Found"},
    [0x307] = {"@Forest of Fall/Maple Sanctuary/Firestarter Kit Purchase"},
    [0x308] = {"@Forest of Fall/Maple Sanctuary/Maple Sanctuary Energy Spore"},
    [0x309] = {"@Forest of Fall/Cryptic Caverns/Cryptic Caverns Wind Essence"},
    [0x30A] = {"@Forest of Fall/Maple Sanctuary/Brick Chimney Wind Essence"},
    [0x30B] = {"@Forest of Fall/Restless Stream/Restless Stream Energy Spore"},
    [0x30C] = {"@Forest of Fall/Cryptic Caverns/Container of Light Found"},
    [0x30D] = {"@Forest of Fall/Cryptic Caverns/Headlamp Acquired"},
    [0x30E] = {"@Forest of Fall/Dark Cave/Dark Cave Energy Spore"},

    -- Lake of Bloom
    [0x400] = {"@Lake of Bloom/Twin Beach/Lake Map Found"},
    [0x401] = {"@Lake of Bloom/Diver's Locus/Essence of Water Purchase"},
    [0x402] = {"@Lake of Bloom/Chungy Cave/Old String Found"},
    [0x403] = {"@Lake of Bloom/Chungy Cave/Chungy Saved"},
    [0x405] = {"@Lake of Bloom/Indigo Island/Indigo Island Energy Spore"},
    [0x406] = {"@Lake of Bloom/Indigo Island/Indigo Island Wind Essence"},
    [0x407] = {"@Lake of Bloom/Indigo Island/Secret Opener Found"},

    -- Grove of Life
    [0x500] = {"@Elder's Home/Grove of Life/Liminal Woods/Grove Map Found"},
    [0x501] = {"@Elder's Home/Screwdriver Purchase"},
    [0x502] = {"@Elder's Home/Grove of Life/Tranquil Garden/Band Aid Found"},
    [0x503] = {"@Elder's Home/Grove of Life/Liminal Woods/Ring of Truth Found"},
    [0x504] = {"@Elder's Home/Grove of Life/Tranquil Garden/Ring of Youth Found"},
    [0x505] = {"@Elder's Home/Grove of Life/Liminal Woods/Ring of Love Found"},
    [0x506] = {"@Elder's Home/Grove of Life/Glowbug Rescue/Ring of Prosperity Found"},
    [0x507] = {"@Elder's Home/Grove of Life/Glowbug Rescue/Ring of Spirit Found"},
    [0x508] = {"@Elder's Home/Grove of Life/Liminal Woods/Sacred Streamer 1 Obtained (Rico)"},
    [0x509] = {"@Elder's Home/Grove of Life/Tranquil Garden/Sacred Streamer 2 Obtained (Web Area)"},
    [0x50A] = {"@Elder's Home/Grove of Life/Brilliant Beach/Sacred Streamer 3 Obtained (Underwater)"},
    [0x50B] = {"@Elder's Home/Grove of Life/Brilliant Beach/Sacred Streamer 4 Obtained (Rings)"},

    -- Mycology
    [0x600] = {"@Garden of Spring/Mycena Entry/Mycena Haematopus"},
    [0x601] = {"@Garden of Spring/Myrtle Pools/Volvopluteus Gloiocephalus"},
    [0x602] = {"@Garden of Spring/Ancient Passage/Hypholoma Capnoides"},
    [0x603] = {"@Garden of Spring/Myrtle Pools/Macrolepiota Procera"},
    [0x604] = {"@Garden of Spring/Anemone Woods/Entoloma Hochstetteri"},
    [0x605] = {"@Garden of Spring/Bolete Beach/Chalciporus Piperatus"},
    [0x606] = {"@Forest of Fall/Water Cave/Coprinus Comatus"},
    [0x607] = {"@Forest of Fall/Dark Cave/Mycena Chlorophos"},
    [0x608] = {"@Forest of Fall/Cryptic Caverns/Cantharellus Cibarius"},
    [0x609] = {"@Forest of Fall/Waxcap Falls/Hygrocybe Flavescens"},
    [0x60A] = {"@Forest of Fall/Cryptic Caverns/Daedaleopsis Tricolor"},
    [0x60B] = {"@Forest of Fall/Waxcap Falls/Amanita Muscaria"},
    [0x60C] = {"@Forest of Fall/Maple Sanctuary/Exsudoporus Frostii"},
    [0x60D] = {"@Lake of Bloom/Sacred Holm/Clavaria Zollingeri"},
    [0x60E] = {"@Lake of Bloom/Sacred Holm/Hygrocybe Conica"},
    [0x60F] = {"@Lake of Bloom/Indigo Island/Lactarius Indigo"},
    [0x610] = {"@Lake of Bloom/Hidden Lotus/Psathyrella Aquatica"},
    [0x611] = {"@Elder's Home/Grove of Life/Liminal Woods/Hygrocybe Miniata"},
    [0x612] = {"@Elder's Home/Coprinellus Disseminatus"},
    [0x613] = {"@Elder's Home/Grove of Life/Tranquil Garden/Phallus Indusiatus"},
    [0x614] = {"@Elder's Home/Grove of Life/Liminal Woods/Laccaria Amethystina"},
    [0x615] = {"@Elder's Home/Grove of Life/Glowbug Rescue/Coprinellus Domesticus"},
    [0x616] = {"@Elder's Home/Grove of Life/Sacred Tree/Heart of the Forest"},

    -- Augmenters
    [0x700] = {"@Garden of Spring/Mycena Entry/Purple Augmenter"},
    [0x701] = {"@Garden of Spring/Anemone Woods/Strawberry Augmenter"},
    [0x702] = {"@Garden of Spring/Mycena Entry/Flower Augmenter"},
    [0x703] = {"@Garden of Spring/Ancient Passage/Secret Augmenter"},
    [0x704] = {"@Forest of Fall/Maple Sanctuary/Verdant Augmenter"},
    [0x705] = {"@Forest of Fall/Dark Cave/Pelagic Augmenter"},
    [0x706] = {"@Forest of Fall/Waxcap Falls/Honey Augmenter"},
    [0x707] = {"@Forest of Fall/Water Cave/Sparkle Augmenter"},
    [0x708] = {"@Lake of Bloom/Diver's Locus/Clavaria Augmenter"},
    [0x709] = {"@Lake of Bloom/Chungy Cave/Ink Augmenter"},
    [0x70A] = {"@Elder's Home/Sharp Augmenter"},
    [0x70B] = {"@Elder's Home/Grove of Life/Brilliant Beach/Precious Augmenter"},
    [0x70C] = {"@Elder's Home/Grove of Life/Glowbug Rescue/Rainbow Augmenter"},
    [0x70D] = {"@Elder's Home/Grove of Life/Tranquil Garden/Veiled Augmenter"},
    [0x70E] = {"@Elder's Home/Grove of Life/Sacred Tree/Sacred Augmenter"}
}